const API_ROOT_PATH = '/api';
const API_DOCS_PATH = '/api-docs';
const HTTP_OK=200
const VALIDATION_ERROR=422
const GENERAL_ERROR=400

export default { API_ROOT_PATH, API_DOCS_PATH, HTTP_OK, VALIDATION_ERROR, GENERAL_ERROR};